name: CI
on:
  - push
  - pull_request
jobs:
  phpstan:
    name: phpstan analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
      - name: phpstan analyze
        run: make phpstan
  suites:
    name: suite tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite-name:
          - sqlite
          - mysql
          - config-regen-currency
        pocketmine-version:
          - "4"
          - "4.0.0"
    steps:
      - uses: actions/checkout@v2
      - run: make suitetest/cases/${{matrix.suite-name}} DIFF="diff -y" POCKETMINE_VERSION=${{matrix.pocketmine-version}}
  fmt:
    name: code style check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
      - run: make fmt EXTRA_FLAGS="--dry-run --diff"
